
import os
import sys
from jinja2 import Template
from src.services.notification_service import send_email_alert

# Path to templates
TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")

class EmailService:
    @staticmethod
    def _render_template(template_name, context):
        """
        Reads an HTML file and replaces placeholders using Jinja2.
        """
        try:
            template_path = os.path.join(TEMPLATE_DIR, template_name)
            with open(template_path, "r", encoding="utf-8") as f:
                template_content = f.read()
            
            template = Template(template_content)
            return template.render(context)
        except Exception as e:
            print(f"❌ Template rendering error for {template_name}: {e}")
            return None

    @staticmethod
    def send_welcome_email(to_email, username, organization, login_url="http://localhost:5173"):
        """
        Sends a welcome email with an embedded dashboard preview image.
        """
        from email.mime.multipart import MIMEMultipart
        from email.mime.text import MIMEText
        from email.mime.image import MIMEImage
        from src.services.notification_service import send_mime_message

        subject = "Welcome to CTDIRP Platform"
        context = {
            "username": username,
            "organization": organization,
            "login_url": login_url
        }
        
        html_content = EmailService._render_template("welcome_email.html", context)
        if not html_content:
            return False

        # Create the root message (related allows html + images)
        msg = MIMEMultipart('related')
        msg['Subject'] = subject
        
        # Encapsulate the plain and HTML versions of the message body in an 'alternative' part
        msgAlternative = MIMEMultipart('alternative')
        msg.attach(msgAlternative)

        msgText = MIMEText('Welcome to CTDIRP. Please enable HTML to view this email.', 'plain')
        msgAlternative.attach(msgText)

        # We reference the image by Content-ID in the HTML: <img src="cid:dashboard_image">
        msgHtml = MIMEText(html_content, 'html')
        msgAlternative.attach(msgHtml)

        # Load and attachment the image
        # email_service.py is in src/services
        # we want backend/static/images
        # dirname(__file__) -> src/services
        # dirname(...) -> src
        # dirname(...) -> backend
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
        img_path = os.path.join(base_dir, "static", "images", "dashboard_preview.png")
        if os.path.exists(img_path):
            try:
                with open(img_path, 'rb') as f:
                    img_data = f.read()
                msgImage = MIMEImage(img_data)
                # Define the image ID
                msgImage.add_header('Content-ID', '<dashboard_image>')
                msgImage.add_header('Content-Disposition', 'inline', filename='dashboard_preview.png')
                msg.attach(msgImage)
            except Exception as e:
                print(f"⚠️ Failed to attach image: {e}")
        else:
             print(f"⚠️ Image not found at {img_path}")

        # Send
        return send_mime_message(msg, to_email)

    @staticmethod
    def send_admin_notification_new_user(admin_email, new_username, organization):
        subject = f"[Alert] New User Registered: {new_username}"
        body = f"A new user '{new_username}' has been created in your organization '{organization}'."
        send_email_alert(subject, body, admin_email)

    @staticmethod
    def send_api_key_confirmation(to_email, key_suffix):
        """
        Confirms to the USER that they generated a key.
        """
        subject = "Security Actions: New API Key Generated"
        body = f"You have successfully generated a new API Key ending in ...{key_suffix}. Keep it safe!"
        send_email_alert(subject, body, to_email)

    @staticmethod
    def send_api_key_admin_alert(admin_email, actor_username, key_suffix):
        """
        Alerts the ADMIN that a user in their org generated a key.
        """
        subject = f"[Security Alert] API Key Generated by {actor_username}"
        body = f"User '{actor_username}' in your organization has generated a new API Key (ending in ...{key_suffix})."
        send_email_alert(subject, body, admin_email)

    @staticmethod
    def send_critical_threat_alert(admin_email, incident_title, incident_id, severity, organization):
        subject = f"[CRITICAL] Threat Detected: {incident_title}"
        body = (
            f"URGENT: A {severity} severity threat has been detected in your organization '{organization}'.\n\n"
            f"Incident ID: {incident_id}\n"
            f"Title: {incident_title}\n\n"
            f"Please log in to the dashboard immediately to investigate."
        )
        send_email_alert(subject, body, admin_email)

    @staticmethod
    def send_password_reset_email(to_email, reset_link):
        subject = "Action Required: Reset Your Password"
        body = (
            f"You requested a password reset for your Administrator account.\n\n"
            f"Click the link below to set a new password:\n"
            f"{reset_link}\n\n"
            f"If you did not request this, please ignore this email."
        )
        send_email_alert(subject, body, to_email)
