
import os
import sys
from datetime import datetime
from jinja2 import Environment, FileSystemLoader, select_autoescape
from src.services.notification_service import send_email_alert

# Path to templates
TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")

# A single environment with a loader enables {% extends %} template inheritance
# (shared base_email.html) and autoescaping of interpolated values (so a value
# like a username can't inject markup into an email).
_jinja_env = Environment(
    loader=FileSystemLoader(TEMPLATE_DIR),
    autoescape=select_autoescape(["html", "xml"]),
)


class EmailService:
    @staticmethod
    def _render_template(template_name, context):
        """
        Render an email template through the shared Jinja2 environment.
        Injects a default `year` so every template's footer stays current.
        """
        try:
            ctx = dict(context or {})
            ctx.setdefault("year", datetime.now().year)
            return _jinja_env.get_template(template_name).render(**ctx)
        except Exception as e:
            print(f"❌ Template rendering error for {template_name}: {e}")
            return None

    @staticmethod
    def send_welcome_email(to_email, username, organization, login_url=None):
        """
        Render and send the branded welcome email.

        The dashboard preview is loaded from a hosted URL in the template, so a
        single HTML body works over both delivery paths (Resend API and SMTP) —
        no MIME image attachment / Content-ID juggling required.
        """
        from datetime import datetime

        if login_url is None:
            login_url = os.getenv("FRONTEND_URL", "http://localhost:5173")

        context = {
            "username": username,
            "organization": organization,
            "login_url": login_url,
            "year": datetime.now().year,
        }

        html_content = EmailService._render_template("welcome_email.html", context)
        if not html_content:
            return False

        return send_email_alert("Welcome to AEGIS LEGION", html_content, to_email)

    @staticmethod
    def send_admin_notification_new_user(admin_email, new_username, organization):
        subject = f"[Alert] New User Registered: {new_username}"
        body = f"A new user '{new_username}' has been created in your organization '{organization}'."
        send_email_alert(subject, body, admin_email)

    @staticmethod
    def send_api_key_confirmation(to_email, key_suffix):
        """
        Confirms to the USER that they generated a key.
        """
        html_content = EmailService._render_template("api_key_email.html", {"key_suffix": key_suffix})
        if not html_content:
            return False
        return send_email_alert("Security: a new API key was generated", html_content, to_email)

    @staticmethod
    def send_api_key_admin_alert(admin_email, actor_username, key_suffix):
        """
        Alerts the ADMIN that a user in their org generated a key.
        """
        html_content = EmailService._render_template(
            "api_key_email.html",
            {"key_suffix": key_suffix, "actor_username": actor_username},
        )
        if not html_content:
            return False
        return send_email_alert(f"Security Alert: API key generated by {actor_username}", html_content, admin_email)

    @staticmethod
    def send_critical_threat_alert(admin_email, incident_title, incident_id, severity, organization):
        subject = f"[CRITICAL] Threat Detected: {incident_title}"
        body = (
            f"URGENT: A {severity} severity threat has been detected in your organization '{organization}'.\n\n"
            f"Incident ID: {incident_id}\n"
            f"Title: {incident_title}\n\n"
            f"Please log in to the dashboard immediately to investigate."
        )
        send_email_alert(subject, body, admin_email)

    @staticmethod
    def send_password_reset_email(to_email, reset_link):
        html_content = EmailService._render_template("password_reset_email.html", {"reset_link": reset_link})
        if not html_content:
            return False
        return send_email_alert("Reset your AEGIS LEGION password", html_content, to_email)
