
import os
import sys
from jinja2 import Template
from src.services.notification_service import send_email_alert

# Path to templates
TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")

class EmailService:
    @staticmethod
    def _render_template(template_name, context):
        """
        Reads an HTML file and replaces placeholders using Jinja2.
        """
        try:
            template_path = os.path.join(TEMPLATE_DIR, template_name)
            with open(template_path, "r", encoding="utf-8") as f:
                template_content = f.read()
            
            template = Template(template_content)
            return template.render(context)
        except Exception as e:
            print(f"❌ Template rendering error for {template_name}: {e}")
            return None

    @staticmethod
    def send_welcome_email(to_email, username, organization, login_url=None):
        """
        Render and send the branded welcome email.

        The dashboard preview is loaded from a hosted URL in the template, so a
        single HTML body works over both delivery paths (Resend API and SMTP) —
        no MIME image attachment / Content-ID juggling required.
        """
        from datetime import datetime

        if login_url is None:
            login_url = os.getenv("FRONTEND_URL", "http://localhost:5173")

        context = {
            "username": username,
            "organization": organization,
            "login_url": login_url,
            "year": datetime.now().year,
        }

        html_content = EmailService._render_template("welcome_email.html", context)
        if not html_content:
            return False

        return send_email_alert("Welcome to AEGIS LEGION", html_content, to_email)

    @staticmethod
    def send_admin_notification_new_user(admin_email, new_username, organization):
        subject = f"[Alert] New User Registered: {new_username}"
        body = f"A new user '{new_username}' has been created in your organization '{organization}'."
        send_email_alert(subject, body, admin_email)

    @staticmethod
    def send_api_key_confirmation(to_email, key_suffix):
        """
        Confirms to the USER that they generated a key.
        """
        subject = "Security Actions: New API Key Generated"
        body = f"You have successfully generated a new API Key ending in ...{key_suffix}. Keep it safe!"
        send_email_alert(subject, body, to_email)

    @staticmethod
    def send_api_key_admin_alert(admin_email, actor_username, key_suffix):
        """
        Alerts the ADMIN that a user in their org generated a key.
        """
        subject = f"[Security Alert] API Key Generated by {actor_username}"
        body = f"User '{actor_username}' in your organization has generated a new API Key (ending in ...{key_suffix})."
        send_email_alert(subject, body, admin_email)

    @staticmethod
    def send_critical_threat_alert(admin_email, incident_title, incident_id, severity, organization):
        subject = f"[CRITICAL] Threat Detected: {incident_title}"
        body = (
            f"URGENT: A {severity} severity threat has been detected in your organization '{organization}'.\n\n"
            f"Incident ID: {incident_id}\n"
            f"Title: {incident_title}\n\n"
            f"Please log in to the dashboard immediately to investigate."
        )
        send_email_alert(subject, body, admin_email)

    @staticmethod
    def send_password_reset_email(to_email, reset_link):
        subject = "Action Required: Reset Your Password"
        body = (
            f"You requested a password reset for your Administrator account.\n\n"
            f"Click the link below to set a new password:\n"
            f"{reset_link}\n\n"
            f"If you did not request this, please ignore this email."
        )
        send_email_alert(subject, body, to_email)
