import requests
import json
import time

BASE_URL = "http://localhost:8000/api"
# Credentials (assuming default seed or passed via env)
USERNAME = "analyst"
PASSWORD = "password"

def run_test():
    print("🚀 Starting API Verification for Assignments...")
    
    # 1. Login
    auth_url = f"{BASE_URL}/token"
    creds_list = [
        ("admin@example.com", "password"),
        ("analyst", "password"),
    ]
    
    token = None
    for usr, pwd in creds_list:
        print(f"   -> Trying login as {usr}...")
        resp = requests.post(auth_url, data={"username": usr, "password": pwd})
        if resp.status_code == 200:
            token = resp.json()["access_token"]
            USERNAME = usr # Update global
            print(f"✅ Login Successful as {usr}")
            break
        else:
            print(f"      Status: {resp.status_code}, Body: {resp.text}")
    
    if not token:
        print("❌ All login attempts failed.")
        return

    headers = {"Authorization": f"Bearer {token}"}

    # 2. Get Incidents (Or Create)
    resp = requests.get(f"{BASE_URL}/incidents/", headers=headers)
    incidents = resp.json() if resp.status_code == 200 else []
    
    if not incidents or not isinstance(incidents, list) or len(incidents) == 0:
        print("⚠️ No incidents found. Creating NEW Test Incident...")
        new_inc = {
            "title": "Test Assignment Incident",
            "description": "Auto-generated by verification script",
            "severity": "low",
            "status": "open"
        }
        resp = requests.post(f"{BASE_URL}/incidents/", params=new_inc, headers=headers)
        if resp.status_code != 200:
            print(f"❌ Failed to create incident: {resp.text}")
            return
        # Fetch again
        incidents = [requests.get(f"{BASE_URL}/incidents/{resp.json()['id']}", headers=headers).json()]
    
    target_incident = incidents[0]
    i_id = target_incident['id']
    print(f"🎯 Target Incident: #{i_id} - {target_incident['title']}")
    
    # 3. Assign to Me
    print(f"   -> Assigning #{i_id} to 'me'...")
    resp = requests.post(f"{BASE_URL}/incidents/{i_id}/assign", json={"assign_to": "me"}, headers=headers)
    
    if resp.status_code == 200:
        print(f"✅ Assignment API Success: {resp.json()}")
    else:
        print(f"❌ Assignment API Failed: {resp.status_code} - {resp.text}")
        return

    # 4. Verify Assignee List
    resp = requests.get(f"{BASE_URL}/incidents/{i_id}", headers=headers)
    updated_incident = resp.json()
    assignees = [a['username'] for a in updated_incident.get('assignees', [])]
    print(f"   -> Current Assignees: {assignees}")
    
    if USERNAME in assignees:
        print("✅ Backend: User is in assignees list.")
    else:
        print("❌ Backend: User failed to be added to assignees.")
        
    # 5. Verify Notification
    print("   -> Checking Notifications...")
    # Wait a moment for async processing if any
    time.sleep(1) 
    resp = requests.get(f"{BASE_URL}/notifications/", headers=headers)
    notifs = resp.json()
    
    # Look for assignment notification
    found = False
    for n in notifs:
        # Title format: "Assigned: #{id}" or similar
        if str(i_id) in n['title'] and "Assign" in n['title']:
            print(f"✅ Notification Found: ID={n['id']}, Title='{n['title']}', Link='{n['link']}'")
            found = True
            break
    
    if not found:
        print("❌ FAIL: No assignment notification found for this incident.")
        print("Recent Notifications:", [n['title'] for n in notifs[:3]])

if __name__ == "__main__":
    run_test()
